DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
  id BIGINT (20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  NAME VARCHAR (30) NULL DEFAULT NULL COMMENT '姓名',
  age INT (11) NULL DEFAULT NULL COMMENT '年龄',
  email VARCHAR (50) NULL DEFAULT NULL COMMENT '邮箱', 
  STATUS INT (1) NOT NULL DEFAULT 1 COMMENT '用户状态（0：禁止，1：正常）',
  create_time TIMESTAMP NOT NULL COMMENT '创建时间',
  modify_time TIMESTAMP NOT NULL COMMENT '更新时间',
  version INT(8) NULL DEFAULT 0 COMMENT '版本',
  mark INT (1) NOT NULL DEFAULT 0 COMMENT '数据状态字段（0：有效，1：无效）',
  PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT = '用户表';
