#
spring:
  profiles:
      # 默认使用开发环境
      active: dev  
  devtools:
     restart:
        additional-paths: src/main/java
        enabled: true
        exclude: templates/**,public/**
  freemarker:
     template-loader-path: classpath:/templates/     
     cache: false
     charset: UTF-8
     suffix: .ftl
     content-type: text/html
      
      
 # Logger Config     
logging:
  config: classpath:logback-spring.xml
  level:
    net.liuzd.spring.boot.v2: debug
  path: d:/logs

resources:
    #应用名称
    appname: spring-boot-example
    #日志打印的基础扫描包
    basepackage: net.liuzd.spring.boot.v2  
    web:
       fastjson: false

 