server:
  port: 80
  session-timeout: 60
  context-path: #/liuzd/

# DataSource Config
spring: 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver  
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: bosPoolName
      max-lifetime: 1800000
      auto-commit: true
      idle-timeout: 30000
      connection-timeout: 30000
