#
spring:
  profiles:
      # 默认使用开发环境
      active: dev  
  devtools:
     restart:
        additional-paths: src/main/java
        enabled: true
        exclude: templates/**,public/**
  freemarker:
     template-loader-path: classpath:/templates/     
     cache: false
     charset: UTF-8
     suffix: .ftl
     content-type: text/html
  data:
     # ES 默认 9300 是 Java 客户端的端口。9200 是支持 Restful HTTP 的接口。
     elasticsearch:
        userIndex: my_user
        userType: my_user
        bookIndex: my_book
        bookType: my_book
        repositories:
           enabled: true
         #访问：http://localhost:9200/信息中的：cluster_name值
        cluster-name: springboot-elasticsearch
        # 配置9200是通过HTTP连接的端口，9300是TCP连接的端口
        cluster-nodes: 127.0.0.1:9300       
      
 # Logger Config     
logging:
  config: classpath:logback-spring.xml
  level:
    net.liuzd.spring.boot.v2: debug
  path: d:/logs

resources:
    #应用名称
    appname: spring-boot-example-es
    #日志打印的基础扫描包
    basepackage: net.liuzd.spring.boot.v2