CREATE TABLE `CUSTOMER` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(255) NOT NULL,
  `DATE_OF_BIRTH` DATETIME NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

INSERT INTO CUSTOMER (ID, FIRST_NAME, DATE_OF_BIRTH) VALUES (1, 'Meredith', '1998-07-13');
INSERT INTO CUSTOMER (ID, FIRST_NAME, DATE_OF_BIRTH) VALUES (2, 'Joan', '1982-10-29');

